import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Trajet from '#models/trajet'

export default class extends BaseSeeder {
  async run() {
    await Trajet.createMany([
      {
        departureStation: 'Paris Gare de Lyon',
        arrivalStation: 'Milano Centrale',
        departureTime: '07:15',
        arrivalTime: '14:30',
        operator: 'TGV INOUI',
        trainType: 'day',
        durationMinutes: 435,
        price: 89.00,
        trainNumber: 'TGV 9243',
        departureCountry: 'France',
        arrivalCountry: 'Italy',
        active: true,
      },
      {
        departureStation: 'Paris Gare de l\'Est',
        arrivalStation: 'München Hbf',
        departureTime: '21:20',
        arrivalTime: '06:45',
        operator: 'ÖBB Nightjet',
        trainType: 'night',
        durationMinutes: 565,
        price: 69.00,
        trainNumber: 'NJ 40469',
        departureCountry: 'France',
        arrivalCountry: 'Germany',
        active: true,
      },
      {
        departureStation: 'Amsterdam Centraal',
        arrivalStation: 'Paris Nord',
        departureTime: '08:17',
        arrivalTime: '11:47',
        operator: 'Thalys',
        trainType: 'day',
        durationMinutes: 210,
        price: 79.00,
        trainNumber: 'THA 9323',
        departureCountry: 'Netherlands',
        arrivalCountry: 'France',
        active: true,
      },
      {
        departureStation: 'Wien Hbf',
        arrivalStation: 'Roma Termini',
        departureTime: '19:10',
        arrivalTime: '09:30',
        operator: 'ÖBB Nightjet',
        trainType: 'night',
        durationMinutes: 860,
        price: 99.00,
        trainNumber: 'NJ 40235',
        departureCountry: 'Austria',
        arrivalCountry: 'Italy',
        active: true,
      },
      {
        departureStation: 'Berlin Hbf',
        arrivalStation: 'Praha hl.n.',
        departureTime: '10:30',
        arrivalTime: '14:50',
        operator: 'DB ICE',
        trainType: 'day',
        durationMinutes: 260,
        price: 49.00,
        trainNumber: 'EC 177',
        departureCountry: 'Germany',
        arrivalCountry: 'Czech Republic',
        active: true,
      },
      {
        departureStation: 'Barcelona Sants',
        arrivalStation: 'Paris Gare de Lyon',
        departureTime: '09:25',
        arrivalTime: '15:53',
        operator: 'Renfe-SNCF',
        trainType: 'day',
        durationMinutes: 388,
        price: 99.00,
        trainNumber: 'AVE 9712',
        departureCountry: 'Spain',
        arrivalCountry: 'France',
        active: true,
      },
      {
        departureStation: 'Zürich HB',
        arrivalStation: 'Hamburg Hbf',
        departureTime: '20:05',
        arrivalTime: '07:05',
        operator: 'ÖBB Nightjet',
        trainType: 'night',
        durationMinutes: 660,
        price: 79.00,
        trainNumber: 'NJ 470',
        departureCountry: 'Switzerland',
        arrivalCountry: 'Germany',
        active: true,
      },
      {
        departureStation: 'London St Pancras',
        arrivalStation: 'Paris Nord',
        departureTime: '07:01',
        arrivalTime: '10:17',
        operator: 'Eurostar',
        trainType: 'day',
        durationMinutes: 136,
        price: 78.00,
        trainNumber: 'EST 9004',
        departureCountry: 'United Kingdom',
        arrivalCountry: 'France',
        active: true,
      },
      {
        departureStation: 'Bruxelles-Midi',
        arrivalStation: 'Köln Hbf',
        departureTime: '11:25',
        arrivalTime: '13:12',
        operator: 'Thalys',
        trainType: 'day',
        durationMinutes: 107,
        price: 55.00,
        trainNumber: 'THA 9451',
        departureCountry: 'Belgium',
        arrivalCountry: 'Germany',
        active: true,
      },
      {
        departureStation: 'Stockholm Central',
        arrivalStation: 'Malmö C',
        departureTime: '22:56',
        arrivalTime: '05:35',
        operator: 'SJ Snälltåget',
        trainType: 'night',
        durationMinutes: 399,
        price: 45.00,
        trainNumber: 'SJ 93',
        departureCountry: 'Sweden',
        arrivalCountry: 'Sweden',
        active: true,
      },
    ])
  }
}